import type { StrictOption } from '@/modules/focus-session/focus-session.types';

import type { Task } from './task.types';

export const prototypeTasks: Task[] = [
  {
    id: 'task-math-review',
    title: '数学套卷错题复盘',
    category: '学习',
    kind: 'goal',
    timerMode: 'countdown',
    estimateMinutes: 50,
    restMinutes: 5,
    deadlineAt: Date.parse('2026-07-31T23:59:59+08:00'),
    targetAmount: 2,
    targetUnit: '套',
    completedAmount: 0.5,
    progressLabel: '目标 0.5/2 套 · 单次 50 分钟',
    mustDo: true,
    forcedTriggerTime: '20:00',
    trustLevel: 'high',
    status: 'pending',
    version: 1,
    syncStatus: 'synced',
    remoteActive: false,
  },
  {
    id: 'task-weekly-report',
    title: '整理周报素材',
    category: '办公',
    kind: 'pomodoro',
    timerMode: 'countdown',
    estimateMinutes: 35,
    restMinutes: 5,
    deadlineAt: null,
    targetAmount: null,
    targetUnit: null,
    completedAmount: 0,
    progressLabel: '倒计时 35 分钟 · 休息 5 分钟',
    mustDo: false,
    forcedTriggerTime: null,
    trustLevel: 'medium',
    status: 'pending',
    version: 1,
    syncStatus: 'synced',
    remoteActive: false,
  },
  {
    id: 'task-english-listening',
    title: '英语听力精听',
    category: '习惯',
    kind: 'pomodoro',
    timerMode: 'countdown',
    estimateMinutes: 25,
    restMinutes: 5,
    deadlineAt: null,
    targetAmount: null,
    targetUnit: null,
    completedAmount: 0,
    progressLabel: '倒计时 25 分钟 · 休息 5 分钟',
    mustDo: true,
    forcedTriggerTime: '21:00',
    trustLevel: 'high',
    status: 'pending',
    version: 1,
    syncStatus: 'synced',
    remoteActive: false,
  },
];

export const prototypeStrictOptions: StrictOption[] = [
  {
    id: 'whitelist',
    label: '仅允许任务白名单',
    description: '仅允许任务所需应用，其他应用无法打开',
    enabled: false,
    capabilityKey: null,
    unavailableReason: '当前版本尚未提供安全的应用白名单',
  },
  {
    id: 'notifications',
    label: '拦截通知',
    description: '专注期间不让消息流把注意力拉走',
    enabled: true,
    capabilityKey: 'blockNotifications',
  },
  {
    id: 'recents',
    label: '隐藏最近任务',
    description: '专注期间从系统最近任务列表隐藏 LoopTodo',
    enabled: false,
    capabilityKey: 'hideRecents',
  },
  {
    id: 'block-leaving',
    label: '阻止离开专注页',
    description: '需要无障碍增强约束，离开后自动返回 LoopTodo',
    enabled: false,
    capabilityKey: 'blockLeaving',
  },
  {
    id: 'launcher-icon',
    label: '隐藏桌面图标（实验性）',
    description: '高风险能力可能导致应用无法重新打开，默认关闭',
    enabled: false,
    capabilityKey: 'hideLauncherIcon',
  },
];
