import type { StrictOption } from '@/modules/focus-session/focus-session.types';

import type { Task } from './task.types';

export const prototypeTasks: Task[] = [
  {
    id: 'task-math-review',
    title: '数学套卷错题复盘',
    category: '学习',
    kind: 'goal',
    timerMode: 'countdown',
    estimateMinutes: 50,
    restMinutes: 5,
    deadlineAt: Date.parse('2026-07-31T23:59:59+08:00'),
    targetAmount: 2,
    targetUnit: '套',
    completedAmount: 0.5,
    progressLabel: '目标 0.5/2 套 · 单次 50 分钟',
    mustDo: true,
    forcedTriggerTime: '20:00',
    trustLevel: 'high',
    status: 'pending',
    version: 1,
    syncStatus: 'synced',
    remoteActive: false, restrictionMode: 'whitelist', whitelistMode: 'inherit', whitelistListId: null, whitelistPackages: [],
  },
  {
    id: 'task-weekly-report',
    title: '整理周报素材',
    category: '办公',
    kind: 'pomodoro',
    timerMode: 'countdown',
    estimateMinutes: 35,
    restMinutes: 5,
    deadlineAt: null,
    targetAmount: null,
    targetUnit: null,
    completedAmount: 0,
    progressLabel: '倒计时 35 分钟 · 休息 5 分钟',
    mustDo: false,
    forcedTriggerTime: null,
    trustLevel: 'medium',
    status: 'pending',
    version: 1,
    syncStatus: 'synced',
    remoteActive: false, restrictionMode: 'whitelist', whitelistMode: 'inherit', whitelistListId: null, whitelistPackages: [],
  },
  {
    id: 'task-english-listening',
    title: '英语听力精听',
    category: '习惯',
    kind: 'pomodoro',
    timerMode: 'countdown',
    estimateMinutes: 25,
    restMinutes: 5,
    deadlineAt: null,
    targetAmount: null,
    targetUnit: null,
    completedAmount: 0,
    progressLabel: '倒计时 25 分钟 · 休息 5 分钟',
    mustDo: true,
    forcedTriggerTime: '21:00',
    trustLevel: 'high',
    status: 'pending',
    version: 1,
    syncStatus: 'synced',
    remoteActive: false, restrictionMode: 'whitelist', whitelistMode: 'inherit', whitelistListId: null, whitelistPackages: [],
  },
];

export const prototypeStrictOptions: StrictOption[] = [
  {
    id: 'whitelist',
    label: '仅允许白名单应用',
    description: '专注期间只允许任务已选择的软件，需要使用情况访问和显示在其他应用上层权限',
    enabled: false,
    capabilityKey: 'whitelist',
    unavailableReason: '需要开启使用情况访问和显示在其他应用上层',
  },
  {
    id: 'notifications',
    label: '拦截通知',
    description: '专注期间不让消息流把注意力拉走',
    enabled: true,
    capabilityKey: 'blockNotifications',
  },
  {
    id: 'recents',
    label: '隐藏最近任务',
    description: '专注期间从系统最近任务列表隐藏 LoopTodo',
    enabled: false,
    capabilityKey: 'hideRecents',
  },
  {
    id: 'block-leaving',
    label: '阻止离开专注页',
    description: '检测到离开后显示全屏拦截页并返回 LoopTodo',
    enabled: false,
    capabilityKey: 'blockLeaving',
  },
  {
    id: 'no-pause',
    label: '禁止暂停',
    description: '开始后必须持续专注，直到计时结束或完成',
    enabled: false,
    capabilityKey: null,
  },
  {
    id: 'no-early-complete',
    label: '禁止提前完成',
    description: '倒计时结束前不能点击完成专注',
    enabled: false,
    capabilityKey: null,
  },
  {
    id: 'no-cancel',
    label: '禁止取消',
    description: '普通专注开始后不能主动放弃',
    enabled: false,
    capabilityKey: null,
  },
  {
    id: 'anti-kill',
    label: '防止应用被系统结束',
    description: 'Android 不允许普通应用保证永不被系统结束',
    enabled: false,
    capabilityKey: null,
    available: false,
    unavailableReason: '设备能力无法保证，请允许自启动和后台运行',
  },
  {
    id: 'launcher-icon',
    label: '隐藏桌面图标（实验性）',
    description: '高风险能力可能导致应用无法重新打开，默认关闭',
    enabled: false,
    capabilityKey: 'hideLauncherIcon',
  },
];
