import { useStore } from 'zustand'; import { createStore } from 'zustand/vanilla';
import { createCompetitionClient, type CompetitionClient } from './competition.client'; import type { LeaderboardEntry, SeasonRank, TeamLeaderboardEntry, TeamMembership } from './competition.types';
type CompetitionStore = { configured: boolean; client: CompetitionClient | null; period: 'today' | 'week' | 'month' | 'season'; rank: SeasonRank | null; leaderboard: LeaderboardEntry[]; membership: TeamMembership; teams: TeamLeaderboardEntry[]; loading: boolean; error: string | null;
  configure(baseUrl: string, token: string): void; load(): Promise<void>; setPeriod(value: CompetitionStore['period']): Promise<void>; createTeam(name: string): Promise<void>; joinTeam(code: string): Promise<void> };
export function createCompetitionStore() { return createStore<CompetitionStore>((set, get) => ({ configured: false, client: null, period: 'today', rank: null, leaderboard: [], membership: null, teams: [], loading: false, error: null,
  configure(baseUrl, token) { set({ configured: true, client: createCompetitionClient(baseUrl, token), error: null }); },
  async load() { const client = get().client; if (!client) return; set({ loading: true, error: null }); try { const [rank, leaderboard, membership, teams] = await Promise.all([client.rank(), client.leaderboard(get().period), client.myTeam(), client.teamLeaderboard()]); set({ rank, leaderboard, membership, teams, loading: false }); } catch (error) { set({ loading: false, error: message(error) }); } },
  async setPeriod(period) { set({ period }); await get().load(); }, async createTeam(name) { await mutate(get, set, (client) => client.createTeam(name)); }, async joinTeam(code) { await mutate(get, set, (client) => client.joinTeam(code)); },
})); }
async function mutate(get: () => CompetitionStore, set: (value: Partial<CompetitionStore>) => void, action: (client: CompetitionClient) => Promise<void>) { const client = get().client; if (!client) return set({ error: '登录后才能使用竞技功能' }); try { await action(client); await get().load(); } catch (error) { set({ error: message(error) }); } }
export const competitionStore = createCompetitionStore(); export function configureCompetition(baseUrl: string, token: string) { competitionStore.getState().configure(baseUrl, token); } export function useCompetitionStore<T>(selector: (state: CompetitionStore) => T) { return useStore(competitionStore, selector); } function message(error: unknown) { return error instanceof Error ? error.message : '竞技操作失败'; }
