import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { ConfigService } from '@nestjs/config'; import { Prisma } from '@prisma/client'; import { createHash } from 'node:crypto'; import { PrismaService } from '../infrastructure/prisma/prisma.service'; import { NotificationService } from '../notifications/notification.service'; import { decryptAddress, encryptAddress } from './address.crypto';
@Injectable() export class RewardService { constructor(private readonly prisma: PrismaService, private readonly config: ConfigService, private readonly notifications: NotificationService) {}
  listRewards() { return this.prisma.reward.findMany({ where: { active: true }, orderBy: { createdAt: 'desc' } }); }
  listClaims(userId: string) { return this.prisma.rewardClaim.findMany({ where: { userId }, include: { reward: true }, orderBy: { createdAt: 'desc' } }); }
  adminClaims() { return this.prisma.rewardClaim.findMany({ include: { reward: true, user: { select: { id: true, email: true, nickname: true } } }, orderBy: { createdAt: 'desc' }, take: 500 }); }
  createReward(adminId: string, input: { name: string; description: string; rewardType: 'virtual' | 'physical'; imageUrl?: string; inventory?: number; config?: Record<string, unknown> }) { if (input.rewardType === 'physical' && input.inventory === undefined) throw new BadRequestException({ code: 'REWARD_INVENTORY_REQUIRED', message: '实物奖励需要库存' }); return this.prisma.reward.create({ data: { ...input, name: input.name.trim(), description: input.description.trim(), config: input.config as Prisma.InputJsonObject ?? {} } }).then(async (reward) => { await this.audit(adminId, null, 'reward_created', reward.id); return reward; }); }
  async grant(adminId: string, rewardId: string, userId: string) { const claim = await this.prisma.$transaction(async (tx) => { const reward = await tx.reward.findUnique({ where: { id: rewardId } }); if (!reward?.active) throw new NotFoundException({ code: 'REWARD_NOT_FOUND', message: '奖励不存在' }); if (reward.rewardType === 'physical') { const reserved = await tx.reward.updateMany({ where: { id: rewardId, inventory: { gt: 0 } }, data: { inventory: { decrement: 1 } } }); if (!reserved.count) throw new ConflictException({ code: 'REWARD_OUT_OF_STOCK', message: '奖励库存不足' }); } return tx.rewardClaim.create({ data: { rewardId, userId } }); }); await this.audit(adminId, claim.id, 'claim_granted', userId); await this.notifications.enqueue({ userId, type: 'reward_available', title: '你获得了 LoopTodo 奖励', body: '请打开奖励页面确认是否接受', data: { claimId: claim.id }, dedupeKey: `reward:${claim.id}`, scheduledAt: new Date() }); return claim; }
  async saveAddress(userId: string, input: { recipient: string; phone: string; address: string }) { const encrypted = encryptAddress(input, this.secret()); const result = await this.prisma.rewardAddress.upsert({ where: { userId }, create: { userId, ...encrypted }, update: encrypted }); await this.audit(userId, null, 'address_updated', encrypted.valueHash); return { updatedAt: result.updatedAt, maskedPhone: maskPhone(input.phone), addressPreview: input.address.slice(0, 6) }; }
  async getAddress(userId: string) { const value = await this.prisma.rewardAddress.findUnique({ where: { userId } }); if (!value) return null; const address = decryptAddress(value.encryptedValue, this.secret()); return { ...address, updatedAt: value.updatedAt }; }
  async accept(userId: string, claimId: string, accept: boolean) { const claim = await this.prisma.rewardClaim.findFirst({ where: { id: claimId, userId, status: 'pending' }, include: { reward: true } }); if (!claim) throw new NotFoundException({ code: 'REWARD_CLAIM_NOT_FOUND', message: '中奖记录不存在或已处理' }); if (accept && claim.reward.rewardType === 'physical' && !(await this.prisma.rewardAddress.findUnique({ where: { userId } }))) throw new BadRequestException({ code: 'REWARD_ADDRESS_REQUIRED', message: '接受实物奖励前请填写收货地址' }); const result = await this.prisma.$transaction(async (tx) => { const updated = await tx.rewardClaim.update({ where: { id: claim.id }, data: { status: accept ? 'accepted' : 'declined', acceptedAt: accept ? new Date() : null } }); if (!accept && claim.reward.rewardType === 'physical') await tx.reward.update({ where: { id: claim.rewardId }, data: { inventory: { increment: 1 } } }); return updated; }); await this.audit(userId, claim.id, accept ? 'claim_accepted' : 'claim_declined', null); return result; }
  async fulfillment(adminId: string, claimId: string) { const claim = await this.prisma.rewardClaim.findFirst({ where: { id: claimId, status: 'accepted', reward: { rewardType: 'physical' } }, include: { reward: true, user: { include: { rewardAddress: true } } } }); if (!claim?.user.rewardAddress) throw new NotFoundException({ code: 'FULFILLMENT_NOT_FOUND', message: '待发放奖励或地址不存在' }); await this.audit(adminId, claim.id, 'address_accessed', claim.user.rewardAddress.valueHash); return { claimId: claim.id, reward: claim.reward.name, address: decryptAddress(claim.user.rewardAddress.encryptedValue, this.secret()) }; }
  async markFulfilled(adminId: string, claimId: string) { const updated = await this.prisma.rewardClaim.updateMany({ where: { id: claimId, status: 'accepted', reward: { rewardType: 'physical' } }, data: { status: 'fulfilled', fulfilledAt: new Date() } }); if (!updated.count) throw new NotFoundException({ code: 'FULFILLMENT_NOT_FOUND', message: '待发放奖励不存在' }); await this.audit(adminId, claimId, 'claim_fulfilled', null); return { fulfilled: true }; }
  private secret() { return this.config.getOrThrow<string>('REWARD_ADDRESS_ENCRYPTION_KEY'); } private audit(actorId: string, claimId: string | null, action: string, target: string | null) { return this.prisma.rewardAudit.create({ data: { actorId, claimId, action, targetHash: target ? createHash('sha256').update(target).digest('hex') : null } }); }
}
function maskPhone(value: string) { return value.length >= 7 ? `${value.slice(0, 3)}****${value.slice(-4)}` : '****'; }
