import { BadRequestException, ConflictException, ForbiddenException, Inject, Injectable, NotFoundException, ServiceUnavailableException, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config'; import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../infrastructure/prisma/prisma.service'; import { PAYMENT_PROVIDERS, type PaymentProviderAdapter } from './payment-provider'; import { entitlementView, extendSubscription, planPrices, type Plan } from './subscription.policy';
import { SecurityAuditService } from '../observability/security-audit.service';

@Injectable() export class SubscriptionService {
  private readonly providers: Map<string, PaymentProviderAdapter>;
  constructor(private readonly prisma: PrismaService, @Inject(PAYMENT_PROVIDERS) providers: PaymentProviderAdapter[], private readonly config: ConfigService, private readonly security: SecurityAuditService) { this.providers = new Map(providers.map((provider) => [provider.name, provider])); }
  async entitlements(userId: string) { const active = await this.activeSubscription(userId); return { ...entitlementView(Boolean(active)), subscription: active }; }
  async assertEntitled(userId: string, entitlement: 'taskAi' | 'familyManagement') { const view = await this.entitlements(userId); if (!view[entitlement]) throw new ForbiddenException({ code: 'VIP_REQUIRED', message: '该功能需要 LoopTodo VIP' }); }
  async assertCanCreateHabit(userId: string) { const view = await this.entitlements(userId); if (view.habitLimit === null) return; const count = await this.prisma.habit.count({ where: { userId, status: 'active' } }); if (count >= view.habitLimit) throw new ForbiddenException({ code: 'HABIT_LIMIT_REACHED', message: '免费版最多创建 3 个习惯' }); }
  async createOrder(userId: string, plan: Plan, idempotencyKey: string) { validateKey(idempotencyKey); const replay = await this.prisma.subscriptionOrder.findUnique({ where: { userId_idempotencyKey: { userId, idempotencyKey } } }); if (replay) return replay;
    const providerName = this.config.get<string>('PAYMENT_PROVIDER') ?? 'test'; if (providerName === 'test' && this.config.get<string>('NODE_ENV') === 'production') throw new ServiceUnavailableException({ code: 'TEST_PAYMENT_DISABLED', message: '生产环境不能使用测试支付' }); const provider = this.providers.get(providerName); if (!provider) throw new ServiceUnavailableException({ code: 'PAYMENT_PROVIDER_UNAVAILABLE', message: '支付 provider 未配置' });
    let order; try { order = await this.prisma.subscriptionOrder.create({ data: { userId, plan, amountCents: planPrices[plan], provider: provider.name, idempotencyKey } }); }
    catch (error) { if (!(error instanceof Prisma.PrismaClientKnownRequestError) || error.code !== 'P2002') throw error; return this.prisma.subscriptionOrder.findUniqueOrThrow({ where: { userId_idempotencyKey: { userId, idempotencyKey } } }); }
    try { const remote = await provider.createOrder({ orderId: order.id, userId, plan, amountCents: order.amountCents, currency: order.currency }); return this.prisma.subscriptionOrder.update({ where: { id: order.id }, data: { externalOrderId: remote.externalOrderId, checkoutUrl: remote.checkoutUrl } }); }
    catch (error) { await this.prisma.subscriptionOrder.update({ where: { id: order.id }, data: { status: 'failed' } }); throw error; }
  }
  async handleWebhook(input: { eventId: string; externalOrderId: string; status: 'paid' | 'failed' }, signature: string) { const payload = canonical(input); const verified = verify(payload, signature, this.config.get<string>('PAYMENT_WEBHOOK_SECRET') ?? ''); const order = await this.prisma.subscriptionOrder.findUnique({ where: { externalOrderId: input.externalOrderId } }); const existing = await this.prisma.paymentAudit.findUnique({ where: { eventId: input.eventId } });
    if (!verified) { if (!existing?.verified) await this.recordAudit(input.eventId, payload, false, 'invalid_signature', order); await this.security.record({ actorId: order?.userId, category: 'payment', action: 'payment_webhook', outcome: 'denied', targetType: 'subscription_order', targetId: order?.id ?? input.externalOrderId, metadata: { eventId: input.eventId, reason: 'invalid_signature' } }); throw new UnauthorizedException({ code: 'INVALID_PAYMENT_SIGNATURE', message: '支付回调签名无效' }); }
    if (!order) { await this.recordAudit(input.eventId, payload, true, 'order_not_found', null); throw new NotFoundException({ code: 'PAYMENT_ORDER_NOT_FOUND', message: '订阅订单不存在' }); }
    if (existing?.verified) return { duplicate: true };
    if (input.status === 'failed') { await this.prisma.subscriptionOrder.update({ where: { id: order.id }, data: { status: 'failed' } }); await this.recordAudit(input.eventId, payload, true, 'failed', order); return { paid: false }; }
    await this.activateOrder(order); await this.recordAudit(input.eventId, payload, true, 'paid', order); return { paid: true };
  }
  async completeTestOrder(userId: string, orderId: string) { if (this.config.get<string>('NODE_ENV') === 'production') throw new ForbiddenException({ code: 'TEST_PAYMENT_DISABLED', message: '生产环境不能完成测试订单' }); const order = await this.prisma.subscriptionOrder.findFirst({ where: { id: orderId, userId, provider: 'test' } }); if (!order) throw new NotFoundException({ code: 'TEST_ORDER_NOT_FOUND', message: '测试订单不存在' }); await this.activateOrder(order); return this.entitlements(userId); }
  private async activateOrder(order: { id: string; userId: string; plan: Plan; externalOrderId: string | null; status: string }) { if (!order.externalOrderId) throw new ConflictException({ code: 'PAYMENT_ORDER_INCOMPLETE', message: '支付订单缺少外部订单号' });
    await this.prisma.$transaction(async (transaction) => { await transaction.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${order.userId}))`; const currentOrder = await transaction.subscriptionOrder.findUniqueOrThrow({ where: { id: order.id } }); if (currentOrder.status === 'paid') return;
      const active = await transaction.subscription.findFirst({ where: { userId: order.userId, expiresAt: { gt: new Date() } }, orderBy: { expiresAt: 'desc' } }); const startsAt = active?.expiresAt && active.expiresAt > new Date() ? active.expiresAt : new Date(); const expiresAt = extendSubscription(startsAt, order.plan);
      await transaction.subscriptionOrder.update({ where: { id: order.id }, data: { status: 'paid', paidAt: new Date() } }); await transaction.subscription.create({ data: { userId: order.userId, plan: order.plan, startsAt, expiresAt, providerOrderId: order.externalOrderId! } }); await transaction.user.update({ where: { id: order.userId }, data: { vipStatus: 'active' } }); }); }
  private async activeSubscription(userId: string) { const active = await this.prisma.subscription.findFirst({ where: { userId, expiresAt: { gt: new Date() } }, orderBy: { expiresAt: 'desc' } }); if (!active) await this.prisma.user.updateMany({ where: { id: userId, vipStatus: 'active' }, data: { vipStatus: 'expired' } }); return active; }
  private async recordAudit(eventId: string, payload: string, verified: boolean, result: string, order: { id: string; userId: string } | null) { await this.prisma.paymentAudit.upsert({ where: { eventId }, create: { eventId, payloadHash: createHash('sha256').update(payload).digest('hex'), verified, result, orderId: order?.id, userId: order?.userId }, update: { payloadHash: createHash('sha256').update(payload).digest('hex'), verified, result, orderId: order?.id, userId: order?.userId } }); }
}
function canonical(input: { eventId: string; externalOrderId: string; status: string }) { return `${input.eventId}.${input.externalOrderId}.${input.status}`; } function verify(payload: string, signature: string, secret: string) { if (!secret || !signature) return false; const expected = createHmac('sha256', secret).update(payload).digest('hex'); const first = Buffer.from(expected); const second = Buffer.from(signature); return first.length === second.length && timingSafeEqual(first, second); } function validateKey(key: string) { if (!key || key.length < 8 || key.length > 160) throw new BadRequestException({ code: 'IDEMPOTENCY_KEY_REQUIRED', message: '请提供有效的 Idempotency-Key' }); }
