import { Body, Controller, Get, Param, Post, Req, UseGuards } from '@nestjs/common'; import { AccessTokenGuard, type AuthenticatedRequest } from '../auth/access-token.guard'; import { AssignFamilyTaskDto, CreateFamilyDto, CreateFamilyInviteDto, CreateTaskChangeRequestDto, FamilyAnomalyDto, JoinFamilyDto, ReviewTaskChangeRequestDto } from './dto/family.dto'; import { FamilyService } from './family.service';
@Controller('family') @UseGuards(AccessTokenGuard) export class FamilyController { constructor(private readonly service: FamilyService) {}
  @Get('groups') groups(@Req() req: AuthenticatedRequest) { return this.service.listGroups(req.auth.sub); } @Post('groups') create(@Req() req: AuthenticatedRequest, @Body() input: CreateFamilyDto) { return this.service.createGroup(req.auth.sub, input.name); }
  @Post('groups/:id/invites') invite(@Req() req: AuthenticatedRequest, @Param('id') id: string, @Body() input: CreateFamilyInviteDto) { return this.service.createInvite(req.auth.sub, id, input.role); } @Post('join') join(@Req() req: AuthenticatedRequest, @Body() input: JoinFamilyDto) { return this.service.join(req.auth.sub, input.code); }
  @Post('groups/:id/tasks') assign(@Req() req: AuthenticatedRequest, @Param('id') id: string, @Body() input: AssignFamilyTaskDto) { return this.service.assignTask(req.auth.sub, id, input); }
  @Post('assignments/:id/change-requests') request(@Req() req: AuthenticatedRequest, @Param('id') id: string, @Body() input: CreateTaskChangeRequestDto) { return this.service.requestChange(req.auth.sub, id, input.requestType, input.reason, input.proposedPatch); }
  @Get('groups/:id/change-requests') requests(@Req() req: AuthenticatedRequest, @Param('id') id: string) { return this.service.listRequests(req.auth.sub, id); } @Post('change-requests/:id/review') review(@Req() req: AuthenticatedRequest, @Param('id') id: string, @Body() input: ReviewTaskChangeRequestDto) { return this.service.reviewChange(req.auth.sub, id, input.decision); }
  @Get('assignments') assignments(@Req() req: AuthenticatedRequest) { return this.service.listAssignments(req.auth.sub); }
  @Get('children/:id/status') status(@Req() req: AuthenticatedRequest, @Param('id') id: string) { return this.service.status(req.auth.sub, id); } @Post('groups/:id/leave') leave(@Req() req: AuthenticatedRequest, @Param('id') id: string) { return this.service.leave(req.auth.sub, id); }
  @Post('anomalies') anomaly(@Req() req: AuthenticatedRequest, @Body() input: FamilyAnomalyDto) { return this.service.reportAnomaly(req.auth.sub, input.type, input.taskId); }
}
